#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://3.144.33.74:3306/root
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      max-active: 20
#
#server:
#  port: 80